#include "../notes.h"

#define SIXTEENTH 157
#define NumNotas 34

short int tune[] = {
NOTE_G4, NOTE_A4, NOTE_B4, NOTE_C5, NOTE_B4, NOTE_D4, NOTE_D4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_D4, NOTE_B4, NOTE_G4, NOTE_D5, NOTE_C5, NOTE_D4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_G4, NOTE_D5, NOTE_B4, NOTE_G5, NOTE_G4, NOTE_B4, NOTE_A4, NOTE_G4, NOTE_D5, NOTE_B4, NOTE_G4, NOTE_D4, NOTE_D4, NOTE_D4, NOTE_G4
};

short int duration[] = {
HALF, QUARTER+EIGHTH, SIXTEENTH, SIXTEENTH, HALF, QUARTER+EIGHTH, EIGHTH, QUARTER+EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER/3, QUARTER/3, QUARTER/3, HALF+QUARTER, QUARTER, QUARTER+EIGHTH, EIGHTH, EIGHTH+SIXTEENTH, SIXTEENTH, EIGHTH+SIXTEENTH, SIXTEENTH, HALF, QUARTER, QUARTER/3, QUARTER/3, QUARTER/3, QUARTER+EIGHTH, SIXTEENTH, SIXTEENTH, QUARTER, EIGHTH+SIXTEENTH, SIXTEENTH, WHOLE
};
